### Get the secret ingredient
GET https://localhost:5091/secret/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InRob21hcyIsInN1YiI6InRob21hcyIsImp0aSI6Ijg5OTBiYzFjIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTIxMCIsImh0dHBzOi8vbG9jYWxob3N0OjUwOTEiLCJodHRwOi8vbG9jYWxob3N0OjUwOTAiXSwibmJmIjoxNzQ2Mzk3OTgzLCJleHAiOjE3NTQzNDY3ODMsImlhdCI6MTc0NjM5Nzk4NCwiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.BhyV-aIyoHL7YZ9LRXIum9YClwt3A5tPD2deAZ5mZ7o